a = input('Digite algo: ')
print(f'O tipo primitivo é: {type(a)}')
print(f'Só tem espaço? {a.isspace()}')
print(f'É número? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'Está em maiúscula? {a.isupper()}')
print(f'Está em minúscula? {a.islower()}')
print(f'Está capitalizada? {a.istitle()}')
